components:
  schemas:
    SemanticValidationRequest:
      type: object
      required:
        - observing_command_input
      properties:
        observing_command_input:
          type: object
          description: Configuration for semantic validation.
          example:
            interface: "https://schema.skao.int/ska-tmc-assignresources/2.1"
            subarray_id: 1
            dish:
              receptor_ids:
                - "SKA001"
                - "SKA002"
            sdp:
              interface: "https://schema.skao.int/ska-sdp-assignres/0.4"
              execution_block:
                eb_id: "eb-test-20220916-00000"
                max_length: 100.0
                context: {}
                beams:
                  - beam_id: "vis0"
                    function: "visibilities"
                scan_types:
                  - scan_type_id: ".default"
                    beams:
                      vis0:
                        channels_id: "vis_channels"
                        polarisations_id: "all"
                      pss1:
                        field_id: "field_a"
                        channels_id: "pulsar_channels"
                        polarisations_id: "all"
                  - scan_type_id: "target:a"
                    derive_from: ".default"
                    beams:
                      vis0:
                        field_id: "field_a"
                channels:
                  - channels_id: "vis_channels"
                    spectral_windows:
                      - spectral_window_id: "fsp_1_channels"
                        count: 14880
                        start: 0
                        stride: 2
                        freq_min: 350000000.0
                        freq_max: 368000000.0
                        link_map:
                          - [0, 0]
                          - [200, 1]
                          - [744, 2]
                          - [944, 3]
                polarisations:
                  - polarisations_id: "all"
                    corr_type: ["XX", "XY", "YY", "YX"]
                fields:
                  - field_id: "field_a"
                    phase_dir:
                      ra: [123, 0.1]
                      dec: [80, 0.1]
                      reference_time: "2023-02-16T01:23:45.678900"
                      reference_frame: "ICRF3"
                    pointing_fqdn: "low-tmc/telstate/0/pointing"
              processing_blocks:
                - pb_id: "pb-mvp01-20200325-00001"
                  script:
                    kind: "realtime"
                    name: "vis_receive"
                    version: "0.1.0"
                  parameters: {}
                - pb_id: "pb-mvp01-20200325-00002"
                  script:
                    kind: "realtime"
                    name: "test_realtime"
                    version: "0.1.0"
                  parameters: {}
                - pb_id: "pb-mvp01-20200325-00003"
                  script:
                    kind: "batch"
                    name: "ical"
                    version: "0.1.0"
                  parameters: {}
                  dependencies:
                    - pb_id: "pb-mvp01-20200325-00001"
                      kind: ["visibilities"]
                  sbi_ids: ["sbi-mvp01-20200325-00001"]
                - pb_id: "pb-mvp01-20200325-00004"
                  script:
                    kind: "batch"
                    name: "dpreb"
                    version: "0.1.0"
                  parameters: {}
                  dependencies:
                    - pb_id: "pb-mvp01-20200325-00003"
                      kind: ["calibration"]
              resources:
                csp_links: [1, 2, 3, 4]
                receptors:
                  - "SKA001"
                  - "SKA002"
        interface:
          type: string
          example: "https://schema.skao.int/ska-tmc-assignresources/2.1"
        sources:
          type: string
          example: "car:ost/ska-ost-osd?2.0.0#tmdata"
        raise_semantic:
          type: boolean
          example: true
        osd_data:
          type: object
          description: Observatory data for validation.
          example:
            observatory_policy:
              cycle_number: 2
              cycle_description: "Science Verification"
              cycle_information:
                cycle_id: "SKAO_2027_1"
                proposal_open: "2026-03-27T12:00:00.000Z"
                proposal_close: "2026-05-12T15:00:00.000Z"
              cycle_policies:
                normal_max_hours: 100.0
              telescope_capabilities:
                Mid: "AA2"
                Low: "AA2"
            capabilities:
              mid:
                AA0.5:
                  available_receivers: [ "Band_1", "Band_2" ]
                  number_ska_dishes: 4
                  number_meerkat_dishes: 0
                  number_meerkatplus_dishes: 0
                  max_baseline_km: 1.5
                  available_bandwidth_hz: 800000000.0
                  cbf_modes: ["correlation", "pst"]
                  number_zoom_windows: 0
                  number_zoom_channels: 0
                  number_pss_beams: 0
                  number_pst_beams: 1
                  ps_beam_bandwidth_hz: 400000000.0
                  number_fsps: 4
                  allowed_channel_width_values: [13440]
                  allowed_channel_count_range_min: 1
                  allowed_channel_count_range_max: 58982
                  number_dish_ids: ["SKA001", "SKA036", "SKA063", "SKA100"]
                basic_capabilities:
                  dish_elevation_limit_deg: 15.0
                  receiver_information:
                    - rx_id: "Band_1"
                      min_frequency_hz: 350000000.0
                      max_frequency_hz: 1050000000.0
                    - rx_id: "Band_2"
                      min_frequency_hz: 950000000.0
                      max_frequency_hz: 1760000000.0
                    - rx_id: "Band_3"
                      min_frequency_hz: 1650000000.0
                      max_frequency_hz: 3050000000.0
                    - rx_id: "Band_4"
                      min_frequency_hz: 2800000000.0
                      max_frequency_hz: 5180000000.0
                    - rx_id: "Band_5a"
                      min_frequency_hz: 4600000000.0
                      max_frequency_hz: 8500000000.0
                    - rx_id: "Band_5b"
                      min_frequency_hz: 8300000000.0
                      max_frequency_hz: 15400000000.0

    SemanticValidationSuccessResponse:
      type: object
      properties:
        status:
          type: integer
          example: 0
        detail:
          type: string
          example: "JSON is semantically valid"
        title:
          type: string
          example: "Semantic validation"

    SemanticValidationErrorResponse:
      type: object
      properties:
        detail:
          type: array
          items:
            type: string
        status:
          type: integer
        title:
          type: string
      example:
        detail:
          - "receptor_ids are too many!Current Limit is 4"
          - "Invalid input for receptor_ids! Currently allowed ['SKA001', 'SKA036', 'SKA063', 'SKA100']"
          - "beams are too many! Current limit is 1"
          - "Invalid function for beams! Currently allowed visibilities"
          - "Invalid input for freq_min"
          - "Invalid input for freq_max"
          - "freq_min should be less than freq_max"
          - "length of receptor_ids should be same as length of receptors"
          - "receptor_ids did not match receptors"
        status: 0
        title: "Semantic Validation Error"

