apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-ost-osd.name" . }}-environment-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-ost-osd.labels" . | indent 4 }}
    component:  {{ template "ska-ost-osd.name" . }}
    domain: environment
    function: ska-ost-osd-environment
    intent: production
data:component
  KUBE_NAMESPACE: {{ .Release.Namespace }}
  ODA_BACKEND_TYPE: {{ .Values.rest.backend.type }}
