{{ if .Values.rest.enabled }}
{{ if .Values.rest.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-ost-osd.labels" . | indent 4 }}
    component: {{ .Values.rest.component }}
    function: {{ .Values.rest.function }}
    domain: {{ .Values.rest.domain }}
    intent: production
  annotations:
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Release.Namespace }}/osd/api
            pathType: Prefix
            backend:
              service:
                name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}
                port:
                  number: 5000
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-ost-osd.labels" . | indent 4 }}
    component: {{ .Values.rest.component }}
    function: {{ .Values.rest.function }}
    domain: {{ .Values.rest.domain }}
    intent: production
spec:
  ports:
  - port: 5000
  selector:
    app: {{ template "ska-ost-osd.name" . }}
    component: {{ .Values.rest.component }}
{{- if .Values.secretProvider.enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: {{ .Values.secretProvider.provider.name }}
  parameters:
    vaultAddress: {{ .Values.secretProvider.provider.vaultAddress }}
    roleName: {{ .Values.secretProvider.provider.roleName }}
    objects: |
{{- range .Values.secretProvider.provider.secrets }}
      - objectName: {{ .secretKey }}
        secretPath: {{ $.Values.secretProvider.provider.secretsPath }}
        secretKey: {{ .secretKey }}
{{- end }}
  secretObjects:
    - secretName: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-id-rsa-credentials
      type: Opaque
      data:
{{- range .Values.secretProvider.provider.secrets }}
        - objectName: {{ .secretKey }}
          key: {{ .secretKey }}
{{- end }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-ost-osd.labels" . | indent 4 }}
    component: {{ .Values.rest.component }}
    function: {{ .Values.rest.function }}
    domain: {{ .Values.rest.domain }}
    intent: production
spec:
  selector:
    matchLabels:
      app: {{ template "ska-ost-osd.name" . }}
      component: {{ .Values.rest.component }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "ska-ost-osd.labels" . | indent 8 }}
        component: {{ .Values.rest.component }}
        function: {{ .Values.rest.function }}
        domain: {{ .Values.rest.domain }}
        intent: production
    spec:
      containers:
      - name: osd
        image: "{{ .Values.rest.image.registry }}/{{ .Values.rest.image.image }}:{{$.Values.rest.image.tag | default $.Chart.AppVersion}}"
        imagePullPolicy: {{ .Values.rest.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
        ports:
          - containerPort: 5000
        env:
        {{- if .Values.secretProvider.enabled }}
        {{- range .Values.secretProvider.provider.secrets }}
          - name: {{ .targetEnv | default .secretKey }}
            valueFrom:
              secretKeyRef:
                name: {{ template "ska-ost-osd.name" $ }}-{{ $.Values.rest.component }}-{{ $.Release.Name }}-id-rsa-credentials
                key: {{ .secretKey }}
          {{- end }}
          {{- else }}
          - name: ID_RSA
            value: "{{ .Values.global.id_rsa }}"
          {{- end }}
        volumeMounts:
          {{- if .Values.secretProvider.enabled }}
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          {{- end }}
        resources:
{{ toYaml .Values.rest.resources | indent 10 }}
      volumes:
        {{- if .Values.secretProvider.enabled }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}
        {{- end }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
{{ end }}
