{{- if .Values.vaultStaticSecret.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ template "ska-ost-osd.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-osd-secret
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: {{ .Values.vaultStaticSecret.mount }}
  path: {{ .Values.vaultStaticSecret.path }}
  destination:
    name: {{ template "ska-ost-osd.bucket-secret-name" . }}
    create: true
    overwrite: true
    excludeRaw: true
    includes:
    {{- range .Values.vaultStaticSecret.secrets }}
      - {{ .secretKey }}
    {{- end }}
  refreshAfter: {{ .Values.vaultStaticSecret.refreshAfter }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ska-ost-osd.bucket-secret-name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  aws_server_bucket_name: "{{ .Values.global.aws_server_bucket_name }}"
  aws_server_public_key: "{{ .Values.global.aws_server_public_key }}"
  aws_server_secret_key: "{{ .Values.global.aws_server_secret_key }}"
  aws_server_bucket_region: "{{ .Values.global.aws_server_bucket_region }}"
  jira_access_token: "{{ .Values.global.jira_access_token }}"
  jira_api_url: "{{ .Values.global.jira_api_url }}"
{{- end }}
