openapi: 3.0.0
info:
  title: OSO Data Archive API
  description: 'This OpenAPI document defines the API for the OSO Data Archive (OSD) REST service'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: 1.0.0
servers:
# This default is overwritten when the application is deployed to include the actual namespace if it is different to the 'ska-osd' default
- url: /ska-oso-osd/api/v2/
paths:
  /osd:
    get:
      summary: Get OSD data filter by the query parameter
      description: |
        Retrieves the OSD data which match the query parameters.
      operationId: ska_oso_osd.rest.api.resources.get_osd
      parameters:
        - $ref: '#/components/parameters/cycle_id'
        - $ref: '#/components/parameters/osd_version'
        - $ref: '#/components/parameters/source'
        - $ref: '#/components/parameters/gitlab_branch'
        - $ref: '#/components/parameters/capabilities'
        - $ref: '#/components/parameters/array_assembly'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "400":
          $ref: '#/components/responses/BadRequest'
        "500":
          $ref: '#/components/responses/InternalServerError'


components:
  parameters:
    cycle_id:
      in: query
      name: cycle_id
      schema:
        type: integer
      required: false
    osd_version:
      in: query
      name: osd_version
      schema:
        type: string
      required: false
    source:
      in: query
      name: source
      schema:
        type: string
      required: false
    gitlab_branch:
      in: query
      name: gitlab_branch
      schema:
        type: string
      required: false
    capabilities:
      in: query
      name: capabilities
      schema:
        type: string
      required: false
    array_assembly:
      in: query
      name: array_assembly
      schema:
        type: string
      required: false

    
  responses:
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequest:
      description: Bad Request, eg validation of against OpenAPI spec failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadRequestResponse'
    UnprocessableEntity:
      description: Unprocessable Entity, semantic error in request eg mismatched IDs
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    BadRequestResponse:
      type: object
      properties:
        status:
          type: integer
        title:
          type: string
        detail:
          type: string
    ErrorResponse:
      type: object
      properties:
        title:
          type: string
        detail:
          type: string
        traceback:
          type: object
          properties:
            key:
              type: string
            type:
              type: string
            full_traceback:
              type: string
