# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-ost-osd

global:
  minikube: true
  cluster_domain: cluster.local

rest:
  component: rest
  function: osd
  domain: operations
  logLevel: info
  enabled: true
  image:
    registry: 192.168.49.2:5000
    image: ska-ost-osd
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu:  100m
      memory: 1024Mi
    limits:
      cpu:  1000m
      memory: 1024Mi
  ingress:
    enabled: true

nodeSelector: {}

affinity: {}

tolerations: []
